/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nexus.app.absorbe;

import chart.data.CSPData;
import chart.spchart.panel.SpectralChartPane;
import java.awt.CardLayout;
import java.awt.image.BufferedImage;
import javax.swing.JSplitPane;
import sps.app.absorb.RateData;
import table.data.TSPData;
import table.std.SPDataTablePane;

/**
 *
 * @author chejf
 */
public class RatePane extends javax.swing.JPanel {

    /**
     * Creates new form RatePane
     */
    public RatePane() {
        initComponents();

        this.InitTableAndChart();
    }

    // <editor-fold defaultstate="collapsed" desc="初始化表格和曲线"> 
    public SPDataTablePane dataTablePane = new SPDataTablePane();

    private SpectralChartPane dataChartPane = new SpectralChartPane();

//    private BaseChartTable baseChartandTable = new BaseChartTable();
    private JSplitPane chartAnddataSplit;

    //初始化表格界面
    private void InitTableAndChart() {
        //设置最大最小范围
        this.dataChartPane.SetMaxRange(65535, -1000);

        //设置左右窗比例
        chartAnddataSplit = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, dataChartPane, null);
        chartAnddataSplit.setResizeWeight(1.0);
        /* 增加显示区域 */
        this.setLayout(new CardLayout());
        this.add(chartAnddataSplit);
    }

    //刷新主曲线
    public void UpdateMainData(RateData main) {
        if (main == null) {
            this.dataChartPane.DisplaySPData("", null);
            this.dataTablePane.UpdateData(null);
        } else {
            this.dataTablePane.UpdateData(new TSPData(main.testdata.data.waveIndex, main.Rate));
            this.dataChartPane.DisplaySPData("main", new CSPData(main.testdata.data.waveIndex, main.Rate));
        }
    }

    //刷新快照
    public void UpdataChartSnapShort(RateData[] sp) {
        String[] name = new String[sp.length];
        CSPData[] data = new CSPData[sp.length];
        for (int i = 0; i < name.length; i++) {
            name[i] = "SP-" + i;
            data[i] = new CSPData(sp[i].testdata.data.waveIndex, sp[i].Rate);
        }
        this.dataChartPane.DisplaySnapShot(name, data);
    }
    
    //清除数据
    public void Clear(){
        this.dataChartPane.CleanChart();
        this.dataTablePane.ClearTable();
    }

    //获取图片
    public BufferedImage GetChartPanePNG() {
        return this.dataChartPane.GetChartPanePNG();
    }

    //显示表格
    public void DisplayTable(boolean value){
        if (value) {
            chartAnddataSplit.setRightComponent(dataTablePane);
        } else {
            chartAnddataSplit.setRightComponent(null);
        }
    }
    // </editor-fold>
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
