/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nexus.app.absorbe;

import chart.data.CSPData;
import chart.spchart.panel.SpectralChartPane;
import java.awt.CardLayout;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.JSplitPane;
import sps.app.absorb.RateData;
import sps.dev.data.SSpectralDataPacket;
import table.data.TSPData;
import table.std.SPDataTablePane;

/**
 *
 * @author chejf
 */
public class SPPane extends javax.swing.JPanel {

    /**
     * Creates new form SPPane
     */
    public SPPane() {
        initComponents();

        this.InitTableAndChart();
        
       
    }

    // <editor-fold defaultstate="collapsed" desc="初始化表格和曲线"> 
    public SPDataTablePane dataTablePane = new SPDataTablePane();

    private SpectralChartPane dataChartPane = new SpectralChartPane();

//    private BaseChartTable baseChartandTable = new BaseChartTable();
    private JSplitPane chartAnddataSplit;

    //初始化表格界面
    private void InitTableAndChart() {
        //设置最大最小范围
        this.dataChartPane.SetMaxRange(65535, -1000);

        //设置左右窗比例
        chartAnddataSplit = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, dataChartPane, null);
        chartAnddataSplit.setResizeWeight(1.0);
        /* 增加显示区域 */
        this.setLayout(new CardLayout());
        this.add(chartAnddataSplit);
    }

    //刷新主曲线
    public void UpdateMainData(SSpectralDataPacket main) {
        this.dataTablePane.UpdateData(new TSPData(main.data.waveIndex, main.data.datavalue));
        this.dataChartPane.DisplaySPData("main", new CSPData(main.data.waveIndex, main.data.datavalue));
    }

    private CSPData refdata = null;
    private final String ref_name = "Ref";

    public void UpdateRefData(SSpectralDataPacket data) {
        this.refdata = new CSPData(data.data.waveIndex, data.data.datavalue);
        this.dataChartPane.DisplaySnapShot(new String[]{ref_name}, new CSPData[]{refdata});
    }

    //刷新快照
    public void UpdataChartSnapShort(RateData[] sp) {
        ArrayList<CSPData> sn_datas = new ArrayList();
        ArrayList<String> sn_namess = new ArrayList();

        sn_datas.add(refdata);
        sn_namess.add(ref_name);
        for (int i = 0; i < sp.length; i++) {
            sn_namess.add("SP-" + i);
            sn_datas.add(new CSPData(sp[i].testdata.data.waveIndex, sp[i].testdata.data.datavalue));
        }
        this.dataChartPane.DisplaySnapShot(sn_namess.toArray(new String[0]), sn_datas.toArray(new CSPData[0]));
    }
    
    //清除数据
    public void Clear(){
        this.dataChartPane.CleanChart();
        this.dataTablePane.ClearTable();
    }

    //获取图片
    public BufferedImage GetChartPanePNG() {
        return this.dataChartPane.GetChartPanePNG();
    }

    //显示表格
    public void DisplayTable(boolean value){
        if (value) {
            chartAnddataSplit.setRightComponent(dataTablePane);
        } else {
            chartAnddataSplit.setRightComponent(null);
        }
    }

    // </editor-fold>
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
