/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nexus.devcie.config;

import java.awt.Frame;
import sps.control.manager.ISpDevice;

/**
 *
 * @author jiche
 */
public class ConfigDialog extends javax.swing.JDialog {

    /**
     * Creates new form SpectralParameterPanel1
     *
     * @param parent
     * @param dev
     */
    public ConfigDialog(Frame parent, ISpDevice dev) {
        super(parent, true);
        initComponents();

        //居中显示
        this.setLocationRelativeTo(parent);

        //int index = SpectralPlatService.GetInstance().GetSingleDevList().GetSelectIndex();
        //SpDevice dev = SpectralPlatService.GetInstance().GetDevManager().ApplyDevice(index);
//        if (this.devcontrol.GetControlState() != CSTATE.CLOSE) {
        SetUpWavePar spPane = new SetUpWavePar();
        spPane.SetCollector(dev);
        TabbedPane.add("光谱系数设置", spPane);
//            
        SetUpLinearPar linearpane = new SetUpLinearPar();
        linearpane.SetCollector(dev);
        TabbedPane.add("非线性系数", linearpane);
//            
            ConfigTablePane lightpane = new ConfigTablePane(dev);
            TabbedPane.add("光源设置", lightpane);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPane;
    // End of variables declaration//GEN-END:variables
}
