/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nexus.devcie.config;

import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import nahon.comm.faultsystem.LogCenter;
import sps.control.manager.ISpDevice;
import sps.dev.data.SSWaveCaculatePar;

/**
 *
 * @author Administrator
 */
public class SetUpWavePar extends javax.swing.JPanel {

    /**
     * Creates new form SPSetPanel
     */
    public SetUpWavePar() {
        initComponents();

        this.Button_SetSWPara.setText("设置");
    }

    private ISpDevice dev;

    public void SetCollector(ISpDevice dev) {//ISPDevConfig config){
        try {
            this.dev = dev;
            this.SpectralParaTable.setModel(new TableWavePar(dev.GetWaveParameter()));
            SpectralParaTable.getTableHeader().setResizingAllowed(false);   // 不允许拉伸
            SpectralParaTable.getTableHeader().setReorderingAllowed(false); //不允许拖拽
            TableColumn column1 = this.SpectralParaTable.getColumnModel().getColumn(0);
            this.SpectralParaTable.getTableHeader().setResizingColumn(column1);
            column1.setWidth(70);
            this.SpectralParaTable.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        } catch (Exception ex) {
            LogCenter.Instance().SendFaultReport(Level.SEVERE, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SpectralParaTable = new javax.swing.JTable();
        Button_SetSWPara = new javax.swing.JButton();

        SpectralParaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(SpectralParaTable);

        Button_SetSWPara.setText("Set");
        Button_SetSWPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SetSWParaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Button_SetSWPara, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_SetSWPara))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SetCParameter() {
        if (this.SpectralParaTable.getCellEditor() != null) {
            this.SpectralParaTable.getCellEditor().stopCellEditing();
        }

        SSWaveCaculatePar tmp = new SSWaveCaculatePar();
        TableWavePar tmpmdl = (TableWavePar) this.SpectralParaTable.getModel();

        tmp.C0 = tmpmdl.parcValue[0];
        tmp.C1 = tmpmdl.parcValue[1];
        tmp.C2 = tmpmdl.parcValue[2];
        tmp.C3 = tmpmdl.parcValue[3];

        try {
            this.dev.SetWaveParameter(tmp);
            JOptionPane.showMessageDialog(this, "设置成功!");
        } catch (Exception ex) {
            LogCenter.Instance().SendFaultReport(Level.SEVERE, ex.getMessage());
        }
    }

    private void Button_SetSWParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SetSWParaActionPerformed
        SetCParameter();
    }//GEN-LAST:event_Button_SetSWParaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_SetSWPara;
    private javax.swing.JTable SpectralParaTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
