/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nexus.app.stander;

import java.awt.Frame;
import java.util.ArrayList;
import sps.app.std.StanderApp;
import sps.app.std.WatchNode;

/**
 *
 * @author jiche
 */
public class WatchNodeDialog extends javax.swing.JDialog {

    /**
     * Creates new form SpectralParameterPanel1
     *
     * @param parent
     * @param dev
     */
    public WatchNodeDialog(Frame parent, StanderApp commapp) {
        super(parent, true);
        initComponents();

        //居中显示
        this.setLocationRelativeTo(parent);

        this.SetAPP(commapp);
    }

    private StanderApp commapp;
    private ArrayList<WatchNode> tmp = new ArrayList();
    private WatchNodeTable node_table;

    public void SetAPP(StanderApp commapp) {
        this.commapp = commapp;

        ArrayList<WatchNode> nodes = this.commapp.GetWatchNode();

        nodes.forEach(node -> {
            if (node == WatchNode.MAXNODE) {
                tmp.add(WatchNode.MAXNODE);
            } else {
                tmp.add(new WatchNode(node));
            }
        });
        node_table = new WatchNodeTable(this.tmp);
        this.Table_nodes.setModel(node_table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_nodes = new javax.swing.JTable();
        Add = new javax.swing.JButton();
        Button_Set = new javax.swing.JButton();
        AddMax = new javax.swing.JButton();
        Del = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Table_nodes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table_nodes);

        Add.setText("+");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Button_Set.setText("确定");
        Button_Set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SetActionPerformed(evt);
            }
        });

        AddMax.setText("+ 峰值点");
        AddMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMaxActionPerformed(evt);
            }
        });

        Del.setText("-");
        Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Del)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_Set, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add)
                    .addComponent(Button_Set)
                    .addComponent(AddMax)
                    .addComponent(Del))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMaxActionPerformed
        if (!this.tmp.contains(WatchNode.MAXNODE)) {
            this.tmp.add(0, WatchNode.MAXNODE);
            this.Table_nodes.updateUI();
        }
    }//GEN-LAST:event_AddMaxActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        this.tmp.add(new WatchNode(0, 0, 65535));
        this.Table_nodes.updateUI();
    }//GEN-LAST:event_AddActionPerformed

    private void DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelActionPerformed
        if (!this.tmp.isEmpty()) {
            this.tmp.remove(this.tmp.size() - 1);
            this.Table_nodes.updateUI();
        }
    }//GEN-LAST:event_DelActionPerformed

    private void Button_SetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SetActionPerformed
        if(this.Table_nodes.getCellEditor() != null){
            this.Table_nodes.getCellEditor().stopCellEditing();
        }  
        this.commapp.AddWatchNode(tmp);
        this.dispose();
    }//GEN-LAST:event_Button_SetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton AddMax;
    private javax.swing.JButton Button_Set;
    private javax.swing.JButton Del;
    private javax.swing.JTable Table_nodes;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
